---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb-operator
helmCharts:
  - name: mariadb-operator-crds
    releaseName: mariadb-operator-crds
    repo: https://mariadb-operator.github.io/mariadb-operator
    version: 25.10.4
    includeCRDs: true
  - name: mariadb-operator
    releaseName: mariadb-operator-helm
    repo: https://mariadb-operator.github.io/mariadb-operator
    version: 25.10.4
    namespace: mariadb-operator
