apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - secrets.yaml
  - datasources.yaml
helmCharts:
  - name: grafana
    releaseName: grafana
    repo: https://grafana.github.io/helm-charts
    version: 10.5.15
    valuesFile: grafana_values.yaml
