apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tempo
resources:
  - secrets.yaml
helmCharts:
  - name: tempo-distributed
    releaseName: tempo
    namespace: tempo
    repo: https://grafana.github.io/helm-charts
    version: 1.61.3
    valuesFile: tempo-values.yaml