apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - ../base
helmCharts:
  - name: vault-secrets-operator
    releaseName: vault-secrets-operator
    namespace: vault
    repo: https://helm.releases.hashicorp.com
    version: "1.2.0"
    valuesFile: values_secrets_operator.yaml
  - name: vault
    releaseName: vault
    namespace: vault
    repo: https://helm.releases.hashicorp.com
    version: "0.32.0"
    valuesFile: values_vault.yaml
