---
- name: Restart Salt Master
  ansible.builtin.service:
    name: salt-master
    state: restarted
    enabled: true

- name: Reload Systemd
  ansible.builtin.command: systemctl daemon-reload
  become: true
  listen: Reload Systemd

- name: Restart Salt Minion
  ansible.builtin.service:
    name: salt-minion
    state: restarted
    enabled: true
