---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-env-local
  namespace: loki
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: alloy
data:
  REGION: fmt2
