---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sentry
resources:
  - database.yaml
helmCharts:
  - name: sentry
    releaseName: sentry
    namespace: sentry
    repo: https://sentry-kubernetes.github.io/charts
    version: 29.3.0
    valuesFile: values.yaml