apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
helmCharts:
  - name: alloy
    releaseName: alloy
    namespace: loki
    repo: https://grafana.github.io/helm-charts
    version: 1.6.0
    valuesFile: alloy-values.yaml
