---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale-operator
resources:
  - ../base
helmCharts:
  - name: tailscale-operator
    releaseName: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.94.2
    namespace: tailscale-operator
    valuesInline:
      includeCRDs: true
      operatorConfig:
        hostname: "tailscale-operator-sea1"
