apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana-operator
helmCharts:
  - name: grafana-agent-operator
    releaseName: grafana-agent-operator
    repo: https://grafana.github.io/helm-charts
    version: 0.5.2
