apiVersion: v1
kind: ConfigMap
metadata:
  name: docspell-config
data:
  # General
  TZ: "America/Los_Angeles"
  DOCSPELL_SERVER_BASE__URL: https://docs.owo.me

  # Server
  DOCSPELL_SERVER_INTERNAL__URL: http://docspell-restserver
  DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET: ""
  DOCSPELL_SERVER_AUTH_SERVER__SECRET: ""
  DOCSPELL_SERVER_BIND_ADDRESS: 0.0.0.0
  DOCSPELL_SERVER_BIND_PORT: "8080"
  DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED: "true"
  DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL: http://solr:8983/solr/docspell
  DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED: "false"
  DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED: "false"
  DOCSPELL_SERVER_BACKEND_SIGNUP_MODE: invite
  DOCSPELL_SERVER_BACKEND_ADDONS_ENABLED: "false"
  DOCSPELL_SERVER_BACKEND_FILES_STORES_DATABASE_ENABLED: "false"
  DOCSPELL_SERVER_BACKEND_FILES_DEFAULT__STORE: "s3"
  DOCSPELL_SERVER_BACKEND_FILES_STORES_S3_ENABLED: "true"
  DOCSPELL_SERVER_BACKEND_FILES_STORES_S3_TYPE: "s3"
  DOCSPELL_SERVER_BACKEND_FILES_STORES_S3_BUCKET: "nepeat-docspell"
  DOCSPELL_SERVER_BACKEND_FILES_STORES_S3_ENDPOINT: "https://s3.us-west-002.backblazeb2.com"
  DOCSPELL_SERVER_BACKEND_FILES_STORES_S3_REGION: ""

  # job server
  DOCSPELL_JOEX_APP__ID: joex1
  DOCSPELL_JOEX_PERIODIC__SCHEDULER_NAME: joex1
  DOCSPELL_JOEX_SCHEDULER_NAME: joex1
  DOCSPELL_JOEX_BASE__URL: http://docspell-joex
  DOCSPELL_JOEX_BIND_ADDRESS: 0.0.0.0
  DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED: "true"
  DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL: http://solr:8983/solr/docspell
  DOCSPELL_JOEX_ADDONS_EXECUTOR__CONFIG_RUNNER: docker,trivial
  DOCSPELL_JOEX_CONVERT_HTML__CONVERTER: Weasyprint
  DOCSPELL_JOEX_FILES_STORES_DATABASE_ENABLED: "false"
  DOCSPELL_JOEX_FILES_DEFAULT__STORE: "s3"
  DOCSPELL_JOEX_FILES_STORES_S3_ENABLED: "true"
  DOCSPELL_JOEX_FILES_STORES_S3_TYPE: "s3"
  DOCSPELL_JOEX_FILES_STORES_S3_BUCKET: "nepeat-docspell"
  DOCSPELL_JOEX_FILES_STORES_S3_ENDPOINT: "https://s3.us-west-002.backblazeb2.com"
  DOCSPELL_JOEX_FILES_STORES_S3_REGION: ""
