apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: librenms
resources:
  - database.yaml
  - config.yaml
  - startup-script.yaml
  - shared-pv.yaml
  - deployment.yaml
  - rrdcached.yaml
  - redis.yaml
  - service.yaml
