---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: librenms-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/target: "sea1-traefik-k8s.generalprogramming.org"
spec:
  rules:
    - host: nms.generalprogramming.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: librenms
                port:
                  number: 80
---
