apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - name: secrets-store-csi-driver
    releaseName: secrets-store-csi-driver
    namespace: kube-system
    version: 1.5.5
    repo: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts