apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd.yaml
  - ceph.yaml
  - loki.yaml
  - promtail.yaml
  - traefik.yaml
  - consul.yaml
  - vault.yaml
  - external-dns.yaml
  - grafana-operator.yaml
  - reloader.yaml
  - tailscale.yaml
  - tempo.yaml
  - kube-state-metrics.yaml
  - monitoring.yaml
  - local-path-storage.yaml
  - cnpg-system.yaml
  - mariadb-operator.yaml
  - shared-db.yaml

  # apps
  - grafana.yaml
  - librenms.yaml
  - docspell.yaml
  - bsky-pds.yaml
  - cerebro.yaml
  - deluge.yaml
  - keycloak.yaml
  - netbox.yaml
  - sentry.yaml

  # users
  - erin/