apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
resources:
  - secrets.yaml
helmCharts:
  - name: loki
    releaseName: loki
    namespace: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.53.0
    valuesFile: loki-values.yaml
