loki:
  auth_enabled: false

  # rate limits
  limits_config:
    ingestion_rate_mb: 10
    ingestion_burst_size_mb: 15
    volume_enabled: true
    allow_structured_metadata: true

  storage:
    type: s3
    s3:
      endpoint: http://radosgw.service.consul
      accessKeyId: ${S3_ACCESS_KEY}
      secretAccessKey: ${S3_SECRET_KEY}
      s3ForcePathStyle: true
      insecure: true
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
  
  schemaConfig:
    configs:
      - from: "2023-08-01"
        store: tsdb
        object_store: s3
        schema: v12
        index:
          prefix: loki_index_
          period: 24h
      - from: "2024-04-28"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_v13_index_
          period: 24h

monitoring:
  selfMonitoring:
    grafanaAgent:
      installOperator: false

gateway:
  service:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: loki.fmt2.generalprogramming.org

backend:
  persistence:
    size: 16Gi
    storageClass: ceph-rbd
  extraArgs:
    - '-config.expand-env=true'
  extraEnv:
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-secrets
          key: s3_access_key
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: loki-secrets
          key: s3_secret_key

read:
  extraArgs:
    - '-config.expand-env=true'
  extraEnv:
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-secrets
          key: s3_access_key
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: loki-secrets
          key: s3_secret_key

write:
  persistence:
    size: 16Gi
  extraArgs:
    - '-config.expand-env=true'
  extraEnv:
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-secrets
          key: s3_access_key
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: loki-secrets
          key: s3_secret_key

chunksCache:
  allocatedMemory: 16384

results_cache:
  allocatedMemory: 8192