---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coder
resources:
  - database.yaml
helmCharts:
  - name: coder
    releaseName: coder
    namespace: coder
    repo: https://helm.coder.com/v2
    version: 2.30.1
    valuesFile: values.yaml
